name: Commscious
favicon: null
layout_spectrum: 0.9338992268312722
typography_spectrum: 0.333189498167485
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3792131969239563
  lightness: 0.42328852601349354
  saturation: 0.6794042016845196
  rhythmicContrast: 0.7500471756793559
purpose: []
